services:
  web:
    build: .
    container_name: fastapi_app
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_app.celery worker --loglevel=info
    env_file: .env
    depends_on:
      - web
      - redis

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${SERVICES_DB_USER}
      POSTGRES_PASSWORD: ${SERVICES_DB_PASSWORD}
      POSTGRES_DB: ${SERVICES_DB_NAME}
    ports:
      - "55432:5432"

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A app.celery_app.celery_app beat --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - web
